[workspace]
resolver = "2"
members = [
    "crates/runtime/stf",
    "crates/sdk/collections",
    "crates/sdk/core",
    "crates/sdk/macros",
    "crates/sdk/server_core",
    "crates/sdk/standards/*",
    "crates/sdk/x/*",
    "crates/testapp",
]

[workspace.package]
repository = "https://github.com/01builders/evolve"
license = "Apache-2.0"
rust-version = "1.81.0"

[workspace.dependencies]
evolve_core = { path = "crates/sdk/core" }
evolve_macros = { path = "crates/sdk/macros" }
evolve_server_core = { path = "crates/sdk/server_core" }
evolve_collections = { path = "crates/sdk/collections" }

evolve_fungible_asset = { path = "crates/sdk/standards/evolve_fungible_asset" }

evolve_scheduler = { path = "crates/sdk/x/scheduler" }
evolve_ns = { path = "crates/sdk/x/ns" }
evolve_block_info = { path = "crates/sdk/x/block_info" }
evolve_token = { path = "crates/sdk/x/token" }
evolve_events = { path = "crates/sdk/x/events" }
evolve_gas = { path = "crates/sdk/x/gas" }
evolve_poa = { path = "crates/sdk/x/poa" }

evolve_stf = { path = "crates/runtime/stf" }

# outside deps
borsh = { features = ["derive"], version = "1.5.5" }

[workspace.lints.rust]
# missing_docs = "deny"

[workspace.lints.rustdoc]
# broken_intra_doc_links = "deny"
# private_intra_doc_links = "deny"
