[workspace]
resolver = "2"
members = [
    "crates/runtime/stf",
    "crates/sdk/evolve_collections",
    "crates/sdk/evolve_core",
    "crates/sdk/evolve_server_core",
]

[workspace.package]
repository = "https://github.com/01builders/evolve"
license = "Apache-2.0"
rust-version = "1.81.0"

[workspace.dependencies]
evolve_core = { path = "crates/sdk/evolve_core" }
evolve_server_core = { path = "crates/sdk/evolve_server_core" }
evolve_collections = { path = "crates/sdk/evolve_collections"}

borsh = { features = ["derive"], version = "1.5.5"}
[workspace.lints.rust]
# missing_docs = "deny"

[workspace.lints.rustdoc]
# broken_intra_doc_links = "deny"
# private_intra_doc_links = "deny"
