[package]
edition = "2024"
license.workspace = true
name = "evolve_share"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
evolve_collections.workspace = true
evolve_core.workspace = true
evolve_fungible_asset.workspace = true
evolve_macros.workspace = true
evolve_testing.workspace = true
evolve_token.workspace = true

borsh.workspace = true
linkme = {version = "0.3", default-features = false, optional = true}

[lints]
workspace = true

[features]
default = []
error-decode = ["linkme", "evolve_core/error-decode"]
