[package]
name = "evolve_events"
version = "0.1.0"
edition = "2021"
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
evolve_core.workspace = true

[lints]
workspace = true
