[package]
edition = "2021"
name = "evolve_rpc"
version = "0.0.1"

license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
evolve_stf.workspace = true

[lints]
workspace = true
