[package]
name = "evolve_scheduler"
version = "0.1.0"
edition = "2021"
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
evolve_collections.workspace = true
evolve_core.workspace = true
evolve_macros.workspace = true
evolve_stf_traits.workspace = true

borsh.workspace = true

[dev-dependencies]
evolve_testing.workspace = true

[lints]
workspace = true
