[package]
name = "evolve_token"
version = "0.1.0"
edition = "2021"
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
evolve_core.workspace = true
evolve_macros.workspace = true
evolve_fungible_asset.workspace = true
evolve_collections.workspace = true

borsh.workspace = true

[dev-dependencies]
evolve_testing.workspace = true

[lints]
workspace = true
