[package]
name = "evolve_scheduler"
version = "0.1.0"
edition = "2021"
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
borsh.workspace = true
evolve_fungible_asset.workspace = true
evolve_collections.workspace = true
evolve_core.workspace = true
evolve_macros.workspace = true
evolve_server_core.workspace = true
evolve_ns.workspace = true

[lints]
workspace = true
