[package]
name = "evolve_unique"
version = "0.1.0"
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
evolve_core.workspace = true
evolve_macros.workspace = true

borsh.workspace = true

[lints]
workspace = true
